spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gakinyoray/springapps-petclinic-microservices.git
        native:
          search-locations: classpath:.
  profiles:
    active: native
